### ISSUE TITLE
Uncaught Error: 'matrix(1, 0, 0, 1, 0, -6.6763e-06)' is not a matrix

### ISSUE THREAD

**Issue by pinyin** [chrvadala/transformation-matrix#12]
Chrome sometimes return transform matrix in an exponential notation, e.g. -6.6763e-06 in this case.
Is this not supported?

**Comment by chrvadala** [comment]
I'm not sure that you're talking about the parse ability but in that case unfortunately is not supported

**Comment by pinyin** [comment]
Yes, I was talking about the `fromString` utility, sorry for the ambiguity.
Thanks for your work.

**Comment by chrvadala** [comment]
The problem is in this line
 https://github.com/chrvadala/transformation-matrix/blob/e3cbd8107476facd01536e251b65991f2baae0e8/src/fromString.js#L5

That regex doesn't support number in that format

You can provide a different Regex to support number formatted in that way.
I think that you can change `(-?[0-9]*\.?[0-9]+)` with `([0-9e-]+)`, but I'm not sure that it's enough safe

**Comment by pinyin** [comment]
OK, I'll try that. Thanks!

**Comment by chrvadala** [comment]
Fixed with 1.8.0
