### ISSUE TITLE
No compose function

### ISSUE THREAD

**Issue by Tanatcu** [chrvadala/transformation-matrix#45]
I tried to import this function. Does not exist.
Have checked sources after. Have not found.
Compose function does not exist in library.
Even search on the whole project have gave just result in REAME.md file.

**Comment by Tanatcu** [comment]
Please, describe function `compose` in transformation-matrix.d.ts file
Imported function shows like undefined function.

**Comment by chrvadala** [comment]
You're right. I will.
In the meantime consider to use `transform`, since `compose` is just an alias
https://github.com/chrvadala/transformation-matrix/blob/master/src/transform.js#L42

**Comment by chrvadala** [comment]
fixed with 1.15.2

**Comment by sjohannes** [comment]
I think [the committed fix][42b4ccc] is incorrect: `compose` should be defined under `transformation-matrix/transform` (because it's in `transform.js`) instead of `transformation-matrix/compose`.

[42b4ccc]: https://github.com/chrvadala/transformation-matrix/commit/42b4ccc3645510bad9587de8a690b319c989ea51#diff-5002198e18b80fa80f98cce302ed3785R141-R147

**Comment by sebinq** [comment]
Can confirm that compose is still fighting with TS :D
